import * as T from './vendor/three.module.js';
import {createMistEnvelopes} from './environment-envelope.js';
const V=(a=0,b=0,c=0)=>new T.Vector3(a,b,c);
let sharedMist;
function rng(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
function smokeTexture(){if(sharedMist)return sharedMist;const c=document.createElement('canvas');c.width=256;c.height=128;const ctx=c.getContext('2d'),r=rng(41);for(let i=0;i<65;i++){const x=r()*220+18,y=r()*78+25,rx=12+r()*45,g=ctx.createRadialGradient(x,y,0,x,y,rx);g.addColorStop(0,`rgba(228,237,230,${.14+r()*.20})`);g.addColorStop(.5,'rgba(222,232,225,.052)');g.addColorStop(1,'rgba(210,225,215,0)');ctx.fillStyle=g;ctx.fillRect(x-rx,y-rx,rx*2,rx*2);}const im=ctx.getImageData(0,0,256,128);for(let y=0;y<128;y++)for(let x=0;x<256;x++){const edge=Math.pow(Math.sin(x/256*Math.PI),2)*Math.pow(Math.sin(y/128*Math.PI),2);im.data[(y*256+x)*4+3]*=edge;}ctx.putImageData(im,0,0);sharedMist=new T.CanvasTexture(c);return sharedMist;}
export function createAtmosphere(scene,options={}){
 const {seed=1,color=0xa3b2aa,mistOpacity=.1,mistCount=12,rain=0,countRain=900,shafts=[],dust=120}=options,bounds=options.mistBounds||{minX:-15,maxX:15,minZ:-20,maxZ:14},r=rng(seed),group=new T.Group(),cards=[],shaftMap=new Map();group.name='Atmosphere';scene.add(group);
 const envelopes=createMistEnvelopes(group,{seed,color:options.envelopeColor??color,envelopes:options.envelopes??[]});
 for(let i=0;i<mistCount;i++){const m=new T.SpriteMaterial({map:smokeTexture(),color,transparent:true,opacity:mistOpacity,depthWrite:false,fog:true}),o=new T.Sprite(m),x=bounds.minX+r()*(bounds.maxX-bounds.minX),z=bounds.minZ+r()*(bounds.maxZ-bounds.minZ),y=i%4===0?1.6+r()*1.2:.25+r()*.65,w=8+r()*14,h=i%4===0?2.2+r()*2:.7+r()*1.15;o.position.set(x,y,z);o.scale.set(w,h,1);o.renderOrder=2;group.add(o);cards.push({o,x,y,z,phase:r()*6.28});}
 for(const spec of shafts){const from=V(...spec.from),to=V(...spec.to),d=from.clone().sub(to),len=d.length(),g=new T.CylinderGeometry(.12,spec.radius||2.6,len,24,1,true),uniforms={time:{value:0},strength:{value:spec.strength??1},tint:{value:new T.Color(spec.color||color)}};const m=new T.ShaderMaterial({uniforms,transparent:true,depthWrite:false,blending:T.AdditiveBlending,side:T.DoubleSide,toneMapped:false,vertexShader:'varying vec3 normalWorld,worldPos;varying vec2 tex;void main(){tex=uv;normalWorld=normalize(mat3(modelMatrix)*normal);worldPos=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(worldPos,1.);}',fragmentShader:'varying vec3 normalWorld,worldPos;varying vec2 tex;uniform float time,strength;uniform vec3 tint;void main(){float facing=abs(dot(normalize(normalWorld),normalize(cameraPosition-worldPos)));float edge=pow(facing,1.9);float end=smoothstep(.0,.17,tex.y)*(1.-smoothstep(.85,1.,tex.y));float streak=.75+.16*sin(tex.x*71.+time*.09)+.09*sin(tex.x*139.-time*.07);float alpha=edge*end*streak*.027*strength;gl_FragColor=vec4(tint,alpha);}'}),o=new T.Mesh(g,m);o.position.copy(from).add(to).multiplyScalar(.5);o.quaternion.setFromUnitVectors(V(0,1,0),d.normalize());o.renderOrder=1;group.add(o);shaftMap.set(spec.id||String(shaftMap.size),{o,uniforms,base:spec.strength??1});}
 const rp=[],fall=[],height=17;for(let i=0;i<countRain;i++){const x=bounds.minX+r()*(bounds.maxX-bounds.minX),z=bounds.minZ+r()*(bounds.maxZ-bounds.minZ),f=r()*height;rp.push(x,0,z,x+.013,-.16-r()*.16,z+.014);fall.push(f,f);}const rg=new T.BufferGeometry();rg.setAttribute('position',new T.Float32BufferAttribute(rp,3));rg.setAttribute('fall',new T.Float32BufferAttribute(fall,1));const ru=T.UniformsUtils.merge([T.UniformsLib.fog,{time:{value:0},opacity:{value:rain*.20}}]),rm=new T.ShaderMaterial({uniforms:ru,transparent:true,depthWrite:false,fog:true,vertexShader:`attribute float fall;uniform float time;varying float alpha;\n#include <fog_pars_vertex>\nvoid main(){vec3 p=position;p.y+=mod(fall-time*8.6+17000.,17.)-.5;p.x+=sin(time*.31+fall)*.045;alpha=smoothstep(-.4,.3,p.y)*(1.-smoothstep(15.,17.,p.y));vec4 mvPosition=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mvPosition;\n#include <fog_vertex>\n}`,fragmentShader:`uniform float opacity;varying float alpha;\n#include <fog_pars_fragment>\nvoid main(){gl_FragColor=vec4(.78,.84,.8,opacity*alpha);\n#include <fog_fragment>\n}`});const drops=new T.LineSegments(rg,rm);group.add(drops);
 const dp=[];for(let i=0;i<dust;i++)dp.push(bounds.minX+r()*(bounds.maxX-bounds.minX),.6+r()*6,bounds.minZ+r()*(bounds.maxZ-bounds.minZ));const dg=new T.BufferGeometry();dg.setAttribute('position',new T.Float32BufferAttribute(dp,3));const dm=new T.PointsMaterial({color:0xc6d3c7,size:.018,transparent:true,opacity:.13,depthWrite:false,fog:true}),mot=new T.Points(dg,dm);group.add(mot);
 function update(t,overrides={}){const clarity=T.MathUtils.clamp(overrides.clarity||0,0,1);envelopes.update(t,clarity);for(const {o,x,y,z,phase} of cards){o.position.set(x+Math.sin(t*.022+phase)*1.3,y+Math.sin(t*.065+phase)*.05,z+Math.cos(t*.017+phase)*.6);o.material.opacity=mistOpacity*(1-clarity*.45)*(.85+Math.sin(t*.08+phase)*.15);}for(const {uniforms} of shaftMap.values())uniforms.time.value=t;ru.time.value=t;ru.opacity.value=(overrides.rain??rain)*.20;mot.position.y=Math.sin(t*.13)*.14;}
 function setLight(id,strength){const s=shaftMap.get(id);if(s)s.uniforms.strength.value=strength;}
 function dispose(){envelopes.dispose();scene.remove(group);group.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose();});}
 return {group,update,setLight,dispose,setEnvelopes:envelopes.setEnvelopes,envelopes:envelopes.volumes};
}
