import * as T from './vendor/three.module.js';
import {loadPoemFont} from './startup-support.js';
import {addBamboo,addBroadleaf} from './plants.js';
import {createAtmosphere} from './atmosphere.js';
import {decorateGardenInk} from './garden-ink-experience.js';
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
function randomSource(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
const shared={};
function texture(kind){
 if(shared[kind])return shared[kind];const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),r=randomSource(kind==='wood'?451:kind==='wall'?731:kind==='tile'?628:826);
 ctx.fillStyle=kind==='wood'?'#877b69':kind==='wall'?'#d4d4c2':kind==='tile'?'#748077':kind==='stone'?'#9aa298':'#8c9a85';ctx.fillRect(0,0,512,512);
 for(let i=0;i<12000;i++){const n=55+r()*170;ctx.fillStyle=`rgba(${n},${n},${n},${.025+r()*.10})`;ctx.fillRect(r()*512,r()*512,kind==='wood'?1+r()*2:1+r()*6,kind==='wood'?8+r()*100:2+r()*6);}
 for(let i=0;i<45;i++){const x=r()*512,y=r()*512,rad=20+r()*100,g=ctx.createRadialGradient(x,y,0,x,y,rad);g.addColorStop(0,`rgba(23,32,24,${r()*.20})`);g.addColorStop(1,'rgba(23,32,24,0)');ctx.fillStyle=g;ctx.fillRect(x-rad,y-rad,rad*2,rad*2);}
 if(kind==='stone'){ctx.strokeStyle='rgba(26,30,24,.24)';ctx.lineWidth=2;for(let row=0;row<8;row++){const yy=row*64;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(512,yy);ctx.stroke();for(let xx=(row%2)*64;xx<512;xx+=128){ctx.beginPath();ctx.moveTo(xx,yy);ctx.lineTo(xx,yy+64);ctx.stroke();}}}
 if(kind==='floor'){for(let row=0;row<6;row++){const yy=row*86;for(let col=-1;col<7;col++){const xx=col*86+(row%2)*43;ctx.fillStyle=`rgba(220,224,202,${.025+r()*.06})`;ctx.fillRect(xx+2,yy+2,82,82);ctx.strokeStyle='rgba(26,40,29,.20)';ctx.lineWidth=2;ctx.strokeRect(xx,yy,86,86);if(r()>.5){ctx.strokeStyle='rgba(38,47,31,.18)';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(xx+20,yy+5);ctx.lineTo(xx+35,yy+28);ctx.lineTo(xx+30,yy+43);ctx.stroke();}}}}
 if(kind==='tile'){for(let row=-1;row<9;row++){const yy=row*64;for(let col=-1;col<14;col++){const xx=col*42+(row%2)*21;ctx.fillStyle=`rgba(31,42,33,${.08+r()*.15})`;ctx.fillRect(xx+1,yy+2,40,62);ctx.strokeStyle='rgba(202,213,188,.20)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(xx+2,yy+4);ctx.quadraticCurveTo(xx+21,yy-3,xx+40,yy+4);ctx.stroke();ctx.strokeStyle='rgba(16,25,19,.30)';ctx.lineWidth=1;ctx.strokeRect(xx,yy+2,42,64);ctx.fillStyle='rgba(131,148,101,.09)';ctx.fillRect(xx+5+r()*20,yy+44,8+r()*14,11);}}}
 const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(kind==='floor'?9:2,kind==='floor'?9:2);t.anisotropy=4;shared[kind]=t;return t;
}
function material(color,kind,extra={}){const map=kind?texture(kind):null;return new T.MeshStandardMaterial({color,roughness:.88,map,bumpMap:map,bumpScale:kind==='wall'?.055:.022,...extra});}
export function buildLycheeScene(){
 const scene=new T.Scene(),root=new T.Group(),walkSurfaces=[];scene.add(root);const random=randomSource(542),clock={},actions=new Set(),levels=new Map(),fruitGroups=[],lanterns=[],rails=[];let sceneTime=0;scene.background=new T.Color(0x53665d);scene.fog=new T.FogExp2(scene.background,.019);scene.userData.saturation=.55;
 const sky=new T.HemisphereLight(0xc8d8cd,0x202a23,.48);scene.add(sky);const sun=new T.DirectionalLight(0xf6e4c5,2.35);sun.position.set(-12,18,-9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,bottom:-24,top:24,near:.1,far:75});sun.shadow.bias=-.00015;sun.shadow.normalBias=.035;sun.shadow.radius=3;sun.target.position.set(6,0,0);scene.add(sun,sun.target);const fill=new T.DirectionalLight(0x9abaae,.34);fill.position.set(14,10,15);scene.add(fill);
 const mats={wood:material(0x514633,'wood'),tile:material(0x465449,'tile',{roughness:.94,bumpScale:.075}),plaster:material(0xc0c5b2,'wall'),stone:material(0x879486,'stone'),floor:material(0x788570,'floor'),paper:material(0xd1c9aa,null),fruit:material(0xc14d32,null,{roughness:.83,bumpMap:texture('stone'),bumpScale:.036})};
 function mesh(g,m,p=V(),parent=root){const o=new T.Mesh(g,m);o.position.copy(p);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 function markWalk(o){o.userData.walkable=true;walkSurfaces.push(o);return o;}
 function box(w,h,d,p,m=mats.wood,parent=root){return mesh(new T.BoxGeometry(w,h,d),m,p,parent);}
 function pole(a,b,r=.06,m=mats.wood,parent=root){const d=b.clone().sub(a),o=mesh(new T.CylinderGeometry(r,r,d.length(),10),m,a.clone().add(b).multiplyScalar(.5),parent);o.quaternion.setFromUnitVectors(V(0,1,0),d.normalize());return o;}
 function roof(x,y,z,w,d,h=1,parent=root){
  for(const side of [-1,1]){const verts=[],uv=[],indices=[],nx=Math.max(12,Math.ceil(w*4)),nz=12;
   const at=(a,b)=>{const u=b/nz,edge=Math.pow(Math.abs(a/nx-.5)*2,7)*u*.25;return V(x+(a/nx-.5)*(w+.75),y+h-u*(h+.32)+u*u*.35+edge,z+side*u*(d/2+.55));};
   for(let a=0;a<=nx;a++)for(let b=0;b<=nz;b++){verts.push(...at(a,b));uv.push(a/nx,b/nz);}
   for(let a=0;a<nx;a++)for(let b=0;b<nz;b++){const n=a*(nz+1)+b;side===1?indices.push(n,n+1,n+nz+1,n+1,n+nz+2,n+nz+1):indices.push(n,n+nz+1,n+1,n+1,n+nz+1,n+nz+2);}
   const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();mesh(g,mats.tile,V(),parent);
   for(let a=0;a<=nx;a+=2){const ps=[];for(let b=0;b<=nz;b++)ps.push(at(a,b));mesh(new T.TubeGeometry(new T.CatmullRomCurve3(ps),12,.026,4,false),mats.tile,V(),parent);}
   pole(at(0,nz),at(nx,nz),.06,mats.wood,parent);for(let a=0;a<nx;a+=2){const p=at(a,nz);const cap=mesh(new T.CylinderGeometry(.071,.071,.12,7).rotateX(Math.PI/2),mats.tile,p,parent);cap.rotation.y=side===1?0:Math.PI;}
  }box(w+.85,.13,.16,V(x,y+h+.08,z),mats.tile,parent);
 }
 function arch(x,z,w=4.4,h=3.2,parent=root){for(const xx of [-w/2,w/2]){box(.23,h,.3,V(x+xx,h/2,z),mats.wood,parent);box(.6,.23,.6,V(x+xx,.11,z),mats.stone,parent);}box(w+.4,.23,.28,V(x,h-.15,z),mats.wood,parent);roof(x,h,z,w+.55,1.4,.55,parent);for(const xx of [-w/2,w/2])pole(V(x+xx,h-1,z),V(x+xx-Math.sign(xx)*.5,h-.12,z),.05,mats.wood,parent);}
 function lantern(x,y,z){const o=box(.38,.62,.38,V(x,y,z),material(0xc8b384,null,{emissive:0xffd19a,emissiveIntensity:.10}));o.name='庭院檐下纸灯笼';for(const a of [-1,1])for(const b of [-1,1])pole(V(x+a*.20,y-.32,z+b*.20),V(x+a*.20,y+.32,z+b*.20),.022);for(let yy=-.20;yy<=.20;yy+=.1)box(.39,.012,.39,V(x,y+yy,z),mats.wood);roof(x,y+.35,z,.6,.55,.19);pole(V(x,y+.55,z),V(x,y+.8,z),.016);const l=new T.PointLight(0xffdbaa,.20,8.5,1.8);l.position.set(x,y,z);root.add(l);lanterns.push({paper:o,light:l});return o;}
 function lattice(x,y,z,w=1.2,h=1.5,parent=root){box(w+.18,h+.18,.14,V(x,y,z),mats.wood,parent);box(w,h,.025,V(x,y,z+.081),material(0x25372d,null),parent);for(let j=-w/2;j<=w/2+.01;j+=.18)box(.028,h,.025,V(x+j,y,z+.105),mats.wood,parent);for(let j=-h/2;j<=h/2+.01;j+=.26)box(w,.021,.03,V(x,y+j,z+.11),mats.wood,parent);}
 const stainCanvas=document.createElement('canvas');stainCanvas.width=stainCanvas.height=128;const stainCtx=stainCanvas.getContext('2d');for(let i=0;i<42;i++){const x=random()*80+24,y=random()*80+24,r=8+random()*27,g=stainCtx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'rgba(41,58,34,.16)');g.addColorStop(1,'rgba(37,52,29,0)');stainCtx.fillStyle=g;stainCtx.fillRect(x-r,y-r,r*2,r*2);}const stainTexture=new T.CanvasTexture(stainCanvas);stainTexture.colorSpace=T.SRGBColorSpace;const stainMat=new T.MeshBasicMaterial({map:stainTexture,transparent:true,opacity:.7,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1});
 function groundStain(x,z,r=1,y=.005){const o=mesh(new T.PlaneGeometry(r*2.1,r*2).rotateX(-Math.PI/2),stainMat,V(x,y,z));o.castShadow=false;return o;}
 function plantedRoots(x,y,z,r=.7){groundStain(x,z,r*1.55,y+.012);for(let i=0;i<5;i++){const a=i*1.256+random()*.25,ps=[V(x,y+.18,z),V(x+Math.cos(a)*r*.33,y+.04,z+Math.sin(a)*r*.33),V(x+Math.cos(a)*r,y+.005,z+Math.sin(a)*r)];mesh(new T.TubeGeometry(new T.CatmullRomCurve3(ps),7,.027,5,false),mats.wood);}}
 function railing(x,y,z,w,parent=root){const group=new T.Group();group.name='园台边缘护栏';parent.add(group);for(let i=0;i<=w;i+=.7)box(.07,.72,.07,V(x-w/2+i,y+.36,z),mats.wood,group);box(.07,.72,.07,V(x+w/2,y+.36,z),mats.wood,group);box(w,.08,.10,V(x,y+.70,z),mats.wood,group);box(w,.065,.08,V(x,y+.27,z),mats.wood,group);rails.push(group);return group;}
 function courtyard(x,z,w,d){markWalk(box(w,.14,d,V(x,-.07,z),mats.floor));for(let xx=-w/2;xx<=w/2;xx+=.75){for(const dz of [-1,1])box(.63,.06,.35,V(x+xx,.02,z+dz*d/2),mats.stone);}for(let zz=-d/2;zz<=d/2;zz+=.75){for(const dx of [-1,1])box(.35,.06,.63,V(x+dx*w/2,.02,z+zz),mats.stone);}}
 // The courtyards sit in a continuous landscape, below the pond water level.
 const land=mesh(new T.PlaneGeometry(220,220).rotateX(-Math.PI/2),material(0x4b6651,'floor',{roughness:.95,bumpScale:.027}),V(4,-.42,0));land.userData.scenery=true;
 const ridgePositions=[],ridgeIds=[],rx=65,rz=18;
 for(let a=0;a<=rx;a++)for(let b=0;b<=rz;b++){const x=-62+a/rx*134,z=-20-b/rz*50,crest=4+Math.sin(x*.085)*2.0+Math.sin(x*.27+1.5)*.6,h=Math.pow(Math.sin(b/rz*Math.PI),1.9)*crest;ridgePositions.push(x,h-.45,z);}
 for(let a=0;a<rx;a++)for(let b=0;b<rz;b++){const n=a*(rz+1)+b;ridgeIds.push(n,n+rz+1,n+1,n+1,n+rz+1,n+rz+2);}
 const ridgeG=new T.BufferGeometry();ridgeG.setAttribute('position',new T.Float32BufferAttribute(ridgePositions,3));ridgeG.setIndex(ridgeIds);ridgeG.computeVertexNormals();mesh(ridgeG,material(0x3d5948,'floor',{roughness:1}));
 const framingTrees=[[-13,-10,8.2],[-10,6,6.5],[-7,18,8.7],[29,5,8.5],[23,-15,10.5],[-7,-16,9],[6,-17,9]];
 framingTrees.forEach(([x,z,h],i)=>addBroadleaf(root,{position:[x,-.42,z],height:h,seed:932+i*29}));
 addBamboo(root,{count:27,bounds:{minX:-28,maxX:29,minZ:-31,maxZ:-21},height:[8,13],seed:752});
 // Low grasses and broken stones anchor the stone platforms to the soil.
 const grassP=[],grassI=[];for(let i=0;i<=7;i++){const u=i/7,w=Math.sin(u*Math.PI)*.035,y=u*.65,z=u*u*.22;grassP.push(-w,y,z,w,y,z);if(i<7){const n=i*2;grassI.push(n,n+2,n+1,n+1,n+2,n+3);}}
 const grassG=new T.BufferGeometry();grassG.setAttribute('position',new T.Float32BufferAttribute(grassP,3));grassG.setIndex(grassI);grassG.computeVertexNormals();const grass=new T.InstancedMesh(grassG,material(0x536e4d,null,{side:T.DoubleSide,roughness:1}),700),go=new T.Object3D();grass.receiveShadow=true;
 for(let i=0;i<700;i++){let x=-14+random()*44,z=-15+random()*37;if(x>-7.7&&x<20.7&&z>-10.7&&z<13.7){x=i%2?-8.4-random()*4:21.6+random()*5;z=-10+random()*26;}go.position.set(x,-.40,z);go.rotation.set((random()-.5)*.3,random()*Math.PI*2,(random()-.5)*.45);go.scale.setScalar(.42+random()*.8);go.updateMatrix();grass.setMatrixAt(i,go.matrix);grass.setColorAt(i,new T.Color().setHSL(.23,.18,.54+random()*.28));}root.add(grass);
 for(let i=0;i<45;i++){const x=i%2?-8.0-random()*3.6:21.0+random()*5,z=-9+random()*27,o=mesh(new T.SphereGeometry(1,9,6),mats.stone,V(x,-.24,z));o.scale.set(.30+random()*.85,.16+random()*.30,.35+random()*.75);o.rotation.y=random()*6.28;}
 // Two connected courtyards, with a real gap that the wooden bridge must span.
 courtyard(-.5,4.5,13,13);courtyard(15.75,3.6,8.5,9.2);box(8.5,1.95,6.7,V(15.75,.925,-6.4),mats.stone);markWalk(box(8.5,.05,6.7,V(15.75,1.975,-6.4),mats.floor));markWalk(box(4,.14,3,V(0,-.07,11.5),mats.floor));
 arch(0,8.1,4.5,3.2);lantern(-1.7,2.15,8.25);lantern(1.7,2.15,8.25);
 // Roofed study porch: the wall is segmented around a working, hinged lattice window.
 const porch=new T.Group();porch.name='可以走进去的书斋';root.add(porch);markWalk(box(13,.2,3.8,V(-.5,.10,-2.7),mats.stone,porch));box(13,3.3,.20,V(-.5,1.85,-4.3),mats.plaster,porch);const beforeStudyRoof=porch.children.length;roof(-.5,3.7,-2.7,13.8,4.1,1.15,porch);const studyCutaway=porch.children.slice(beforeStudyRoof);
 for(let x=-6;x<=5.6;x+=2.3){pole(V(x,.2,-.85),V(x,3.74,-.85),.115,mats.wood,porch);box(2.15,.09,.12,V(x+1.05,3.08,-.85),mats.wood,porch);}
 studyCutaway.push(box(2.9,3.2,.18,V(-5.55,1.8,-1),mats.plaster),box(.9,3.2,.18,V(-.95,1.8,-1),mats.plaster),box(4.45,3.2,.18,V(3.325,1.8,-1),mats.plaster),box(2.7,.55,.18,V(-2.75,.47,-1),mats.plaster),box(2.7,.53,.18,V(-2.75,3.18,-1),mats.plaster));
 const doorFrame=new T.Group();doorFrame.name='书斋真实房门 · 与窗分开';root.add(doorFrame);for(const x of [-.52,1.12])box(.12,3.2,.20,V(x,1.8,-1),mats.wood,doorFrame);box(1.76,.16,.20,V(.3,3.33,-1),mats.wood,doorFrame);markWalk(box(1.6,.10,.34,V(.3,.15,-.84),mats.stone));
 const shutters=[];for(const side of [-1,1]){const sh=new T.Group();sh.position.set(-2.75+side*1.35,.75,-.88);root.add(sh);const center=-side*.65;box(1.27,2.10,.06,V(center,1.05,0),mats.wood,sh);for(let i=0;i<6;i++)box(.028,2.05,.045,V(center-.5+i*.2,1.05,.065),mats.paper,sh);for(let y=.23;y<2.1;y+=.25)box(1.25,.018,.045,V(center,y,.07),mats.paper,sh);shutters.push({g:sh,side});}
 const desk=box(1.8,.13,.8,V(-2.7,.89,-2.15),mats.wood);desk.name='书斋内的木案';for(const x of [-3.4,-2])for(const z of [-2.45,-1.85])box(.09,.81,.09,V(x,.43,z));const deskPaper=box(1.25,.022,.50,V(-2.75,.97,-2.13),mats.paper);deskPaper.name='书斋案上的原纸';
 for(const {g}of shutters)for(const object of g.children)studyCutaway.push(object);const cutawayMaterials=new Map();for(const object of studyCutaway){if(!object.isMesh)continue;const original=object.material;if(!cutawayMaterials.has(original)){const copy=original.clone();copy.transparent=true;cutawayMaterials.set(original,copy);}object.material=cutawayMaterials.get(original);}
 // Left boundary, small side room and eastern courtyard pavilion frame the route.
 box(.3,2.55,12,V(-7.15,1.275,3.2),mats.plaster);const wallCap=new T.Group();wallCap.position.set(-7.15,0,3.2);wallCap.rotation.y=Math.PI/2;root.add(wallCap);roof(0,2.55,0,12,.3,.3,wallCap);box(4.0,3.25,3.4,V(-5.1,1.625,11.5),mats.plaster);roof(-5.1,3.4,11.5,4.5,3.8,.85);
 box(.3,2.7,10,V(20.4,1.35,2.5),mats.plaster);box(8.5,2.25,.25,V(15.75,3.15,-10.1),mats.plaster);roof(15.75,4.3,-10.1,9.0,.5,.5);arch(16,6.8,3.7,3.1);
 const topRailLeft=railing(12.975,2.04,-3.2,2.85),topRailRight=railing(18.775,2.04,-3.2,2.35);topRailLeft.name='台顶左栏 · 让出中央楼梯';topRailRight.name='台顶右栏 · 让出中央楼梯';
 for(const x of [11.55,19.95]){const sideRail=railing(0,0,0,6.4);sideRail.name='台地两侧连续护栏';sideRail.position.set(x,2.04,-6.4);sideRail.rotation.y=Math.PI/2;}
 // A pond remains below the moving drawbridge. Its ripple shader uses scene fog.
 const pondMaterial=new T.ShaderMaterial({fog:true,uniforms:T.UniformsUtils.merge([T.UniformsLib.fog,{time:{value:0},inkAge:{value:-1},inkPower:{value:0},rippleOrigin:{value:new T.Vector2(.142,.20)}}]),vertexShader:`varying vec2 p;\n#include <fog_pars_vertex>\nvoid main(){p=uv;vec4 mvPosition=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*mvPosition;\n#include <fog_vertex>\n}`,fragmentShader:`varying vec2 p;uniform float time,inkAge,inkPower;uniform vec2 rippleOrigin;\n#include <fog_pars_fragment>\nvoid main(){float wave=pow(sin(p.y*93.+sin(p.x*23.)+time*.5)*.5+.5,10.);float d=length((p-rippleOrigin)*vec2(5.5,12.));float age=max(0.,inkAge);float front=exp(-pow((d-age*.82)/.26,2.));float rings=sin(d*17.-age*11.)*front*exp(-age*.23)*inkPower*step(0.,inkAge);vec3 base=vec3(.045,.085,.068)+wave*.020;gl_FragColor=vec4(base+vec3(.11,.16,.125)*rings,1.);\n#include <fog_fragment>\n}`});const pond=mesh(new T.PlaneGeometry(5.5,12).rotateX(-Math.PI/2),pondMaterial,V(8.75,-.20,3.4));pond.name='毛笔触水后向外荡开的庭院水面';
 const lotus=[];
 const petalShape=new T.Shape();petalShape.moveTo(0,0);petalShape.quadraticCurveTo(-.16,.23,0,.52);petalShape.quadraticCurveTo(.16,.23,0,0);const petalGeometry=new T.ShapeGeometry(petalShape,14),leafMaterial=material(0x6e8d65,null,{side:T.DoubleSide,roughness:.94}),petalMaterial=material(0xc9b8a8,null,{side:T.DoubleSide,roughness:.87});
 for(const [i,[x,z]]of [[6.86,7.6],[7.3,5.85],[10.56,7.98],[9.45,8.65]].entries()){const leaf=mesh(new T.CircleGeometry(.40+i*.025,36).rotateX(-Math.PI/2),leafMaterial,V(x,-.177,z));leaf.scale.set(.05,1,.05);leaf.rotation.y=i*1.77;leaf.name='落墨后展开的荷叶';const flower=new T.Group();flower.position.set(x+.18,-.12,z-.17);flower.name='水纹唤开的荷花';root.add(flower);const petals=[];for(let j=0;j<8;j++){const turn=new T.Group();turn.rotation.y=j*Math.PI/4;flower.add(turn);const p=mesh(petalGeometry,petalMaterial,V(),turn);p.rotation.x=.02;p.scale.set(.32,.66,.32);p.castShadow=false;petals.push(p);}mesh(new T.SphereGeometry(.064,12,8),material(0xb8a66f,null),V(0,.095,0),flower);flower.scale.setScalar(.06);lotus.push({leaf,flower,petals,delay:i*.10});}
 for(const x of [6,11.5])box(.20,.24,12,V(x,-.04,3.4),mats.stone);
 const bridge=new T.Group();bridge.position.set(5.95,.02,3);bridge.rotation.z=Math.PI/2;root.add(bridge);for(let i=0;i<25;i++){markWalk(box(.22,.13,2.2,V(.13+i*.22,0,0),mats.wood,bridge));}for(const z of [-1.02,1.02]){box(5.45,.18,.11,V(2.7,-.06,z),mats.wood,bridge);for(let i=0;i<6;i++)pole(V(i*1.08,.02,z),V(i*1.08,.80,z),.035,mats.wood,bridge);pole(V(0,.80,z),V(5.4,.80,z),.025,mats.wood,bridge);}
 const lever=new T.Group();lever.position.set(4.6,0,3);root.add(lever);box(.5,.8,.5,V(0,.4,0),mats.stone,lever);pole(V(0,.85,0),V(.25,1.4,0),.045,mats.wood,lever);const seal=mesh(new T.CircleGeometry(.22,32),material(0xcfcaae,null,{emissive:0x899b75,emissiveIntensity:.5}),V(0,.63,.27),lever);seal.rotation.x=.06;
 // Five broad stone treads join the lower courtyard to the orchard terrace.
 for(let i=0;i<12;i++){const y=(i+1)/6,z=2.75-i*.5;const tread=markWalk(box(3.05,y,.52,V(16,y/2,z),mats.stone));tread.name='连续登台石阶_'+i;for(const x of [14.35,17.65])box(.16,y+.75,.18,V(x,(y+.75)/2,z),mats.stone);}for(const x of [14.35,17.65]){const handrail=pole(V(x,.98,3),V(x,2.82,-3),.055,mats.wood);handrail.name='斜楼梯扶手';pole(V(x,2.82,-3),V(x,2.74,-3.2),.055,mats.wood);}
 // The study window releases a wind-trail toward the bridge control.
 const branch=new T.Group();branch.position.set(-2.5,0,-.15);root.add(branch);const branchCurve=new T.CatmullRomCurve3([V(-1.6,2.0,0),V(-.6,2.3,0),V(.1,2.25,0),V(.8,1.8,.1)]);mesh(new T.TubeGeometry(branchCurve,24,.025,7,false),mats.wood,V(),branch);for(let i=0;i<16;i++){const t=i/16,p=branchCurve.getPoint(t),leaf=mesh(new T.SphereGeometry(1,6,4),material(0x527252,null),p,branch);leaf.scale.set(.055,.025,.16);leaf.rotation.y=t*8;}
 const windPositions=[];for(let i=0;i<140;i++)windPositions.push(random(),random(),random());const windG=new T.BufferGeometry();windG.setAttribute('position',new T.Float32BufferAttribute(windPositions,3));const wind=new T.Points(windG,new T.PointsMaterial({color:0xe7ead6,size:.032,transparent:true,opacity:0,depthWrite:false}));root.add(wind);
 // One low cluster, one wind-fallen cluster, and one cluster above the stairs.
 const treePlaces=[[-1,0,4],[-5,0,1.2],[18,2,-6]],picks=[[-1,0,5.3],[-3,0,1.4],[18,2,-4.8]],fruitIds=['fruit-low','fruit-fall','fruit-high'];
 treePlaces.forEach((p,i)=>{addBroadleaf(root,{position:p,height:i===2?6.1:i===1?5.8:5.7,seed:726+i*33});const fg=new T.Group();fg.position.fromArray(picks[i]);fg.position.y=i===1?3.5:picks[i][1]+1.72;root.add(fg);fruitGroups.push(fg);if(i!==1){const b=new T.CatmullRomCurve3([V(0,.0,-1.2),V(.20,.30,-.65),V(.28,.21,-.1),V(.10,0,.35)]);mesh(new T.TubeGeometry(b,18,.038,7,false),mats.wood,V(),fg);}for(let j=0;j<9;j++){const a=j*2.399,r=.09+random()*.23,o=mesh(new T.SphereGeometry(.11+random()*.026,12,8),mats.fruit,V(Math.cos(a)*r,-.15-Math.floor(j/3)*.17,Math.sin(a)*r+.22),fg);o.scale.y=1.13;if(i!==1)pole(V(.12,0,.25),o.position,.008,mats.wood,fg);}});

 addBamboo(root,{count:14,bounds:{minX:-13,maxX:-8,minZ:-10,maxZ:7},height:[6,9],seed:963});addBamboo(root,{count:11,bounds:{minX:23,maxX:28,minZ:-13,maxZ:6},height:[6,9],seed:285});
 const stoneGeometry=new T.SphereGeometry(1,8,6);for(let i=0;i<32;i++){const o=mesh(stoneGeometry,mats.stone,V(i<16?-6.7+random()*.8:19.7+random()*.65,.10,-1+random()*10));o.scale.set(.13+random()*.2,.1+random()*.13,.12+random()*.3);o.rotation.y=random()*6.28;}
 const targets=[
  {id:'window',position:[-3,0,0],radius:1.65,label:'书斋的窗',verb:'以笔引风，打开窗扇',hint:'窗挡住了风。在真实窗闩的墨点上按住片刻，再松笔；风会吹落枝上的果。',feedback:'窗扇打开，风穿过书斋，枝上的荔枝落进庭中。',verse:'罗浮山下四时春',kind:'spatial-gesture',type:'brush'},
  {id:'bridge',position:[4.6,0,3],radius:1.65,label:'桥头木闸',verb:'让木桥落到对岸',hint:'对岸还隔着水。按住桥头石座的墨点片刻，松筆等木桥落稳，再过桥登台。',feedback:'木桥落稳了，两座庭院连在了一起。',verse:'卢橘杨梅次第新',kind:'spatial-gesture',type:'brush'},
  {id:'lamp',position:[-1.7,0,7.1],radius:1.6,label:'门廊的灯笼',verb:'添一笔暖光',hint:'门廊灯还暗着。笔尖在纸灯的墨点上稍停再松开；重墨会留下更暖的灯光。',feedback:'灯笼亮了，廊下和石砖上有了暖光。',kind:'spatial-gesture',type:'brush'},
  {id:'pond',position:[4.9,0,6.65],radius:1.6,label:'池边的荷叶',verb:'让静水泛起波纹',hint:'池水很静。走到池边，把笔尖停在水面的淡墨点上，再松笔；水纹会带开荷叶。',feedback:'水纹向外荡开，荷叶和花慢慢舒展。',kind:'spatial-gesture',type:'brush'},
  {id:'fruit-low',position:picks[0],label:'低枝上的荔枝',verb:'伸手摘下荔枝',kind:'collect',type:'pick'},
  {id:'fruit-fall',position:picks[1],label:'风落的荔枝',verb:'拾起落在庭中的荔枝',kind:'collect',type:'pick',requires:['window']},
  {id:'fruit-high',position:picks[2],label:'台地上的荔枝',verb:'摘下高处的荔枝',kind:'collect',type:'pick',requires:['bridge']},
  {id:'poem',position:[16,2,-8.2],radius:1.55,label:'园中的石案',verb:'将这一程写下来',hint:'三处荔枝都摘过了。走到石案旁，在纸上落墨，让这首诗留在庭院里。',feedback:'诗写在石案的纸上了。还可以回到庭中，看看灯和池水。',verse:'日啖荔枝三百颗，不辞长作岭南人',kind:'spatial-gesture',type:'brush',requires:['fruit-low','fruit-fall','fruit-high']}
 ];

 const poemTable=box(1.9,.12,1,V(16,2.8,-9.1),mats.stone);poemTable.name='庭院题诗石案';for(const x of [15.3,16.7])box(.18,.8,.75,V(x,2.4,-9.1),mats.stone);const poemPaper=box(1.4,.018,.66,V(16,2.873,-9.1),mats.paper);poemPaper.name='石案上的题诗纸';
 const poemCanvas=document.createElement('canvas');poemCanvas.width=2048;poemCanvas.height=1024;const poemContext=poemCanvas.getContext('2d'),poemTexture=new T.CanvasTexture(poemCanvas);poemTexture.colorSpace=T.SRGBColorSpace;function paintGardenPoem(){poemContext.clearRect(0,0,2048,1024);poemContext.font='224px Poem, serif';poemContext.textAlign='center';poemContext.textBaseline='middle';poemContext.fillStyle='#39402d';poemContext.fillText('日啖荔枝三百颗',1024,320);poemContext.fillText('不辞长作岭南人',1024,680);poemTexture.needsUpdate=true;}paintGardenPoem();loadPoemFont().then(paintGardenPoem);
 const poemLetters=mesh(new T.PlaneGeometry(1.36,.62).rotateX(-Math.PI/2),new T.MeshBasicMaterial({map:poemTexture,transparent:true,opacity:0,depthWrite:false,toneMapped:false}),V(16,2.887,-9.1));poemLetters.name='题诗后留在真实纸面的荔枝诗';poemLetters.castShadow=false;
 const windowLatch=box(.14,.22,.10,V(-1.25,.97,.14),mats.wood,shutters[1].g);windowLatch.name='随真实窗扇转开的木窗闩';
 const cameraZones=[{id:'study',type:'perspective',position:[2.4,2.55,-3.35],lookAt:[-2.55,1.20,-1.95],fov:43,test:p=>p.x<5.9&&p.z<-1.12},{id:'entry',type:'perspective',position:[0,4.8,28],lookAt:[0,1.7,3.8],test:p=>p.x<11.5&&p.z>6.5},{id:'court',type:'perspective',position:[24,8,23],lookAt:[6,1.9,1.5],height:15.5,test:p=>p.x<11.5&&p.z<=6.5},{id:'orchard',type:'perspective',position:[16,8,18],lookAt:[16,3,-6],test:p=>p.x>=11.5}];
 const bounds={minX:-6.65,maxX:20,minZ:-9.3,maxZ:13},contains=(p,a,b,c,d)=>p.x>=a&&p.x<=b&&p.z>=c&&p.z<=d;
 function heightAt(x,z){if(x>=-6.7&&x<=5.9&&z>=-4.05&&z<-.72)return .20;if(x>=14.48&&x<=17.52&&z>=-3.05&&z<=3.02)return Math.max(0,Math.min(2,Math.ceil((3-z)*2)/6));if(x>=11.5&&x<=20&&z<-3)return 2;return 0;}
 function canMove(from,to,done=actions){
  const has=id=>typeof done?.has==='function'?done.has(id):Array.isArray(done)?done.includes(id):Boolean(done?.[id]);
  if(Math.abs(heightAt(to.x,to.z)-heightAt(from.x,from.z))>.25)return false;
  if(to.x<6&&to.z<-.58){if(!contains(to,-6.65,5.75,-4.05,-.58)||contains(to,-3.73,-1.67,-2.68,-1.63))return false;const lo=Math.min(from.z,to.z),hi=Math.max(from.z,to.z);if(lo<-.88&&hi>-1.12){const dz=to.z-from.z;for(const z of [-1.12,-.88]){const u=Math.abs(dz)<1e-8?0:T.MathUtils.clamp((z-from.z)/dz,0,1),x=T.MathUtils.lerp(from.x,to.x,u);if(x<-.36||x>.68)return false;}}return true;}
  if(contains(to,-7,-3,9.8,13.2))return false;
  if(contains(to,-6.65,5.95,-.58,10.7))return true;
  if(contains(to,-2,2,10,13))return true;
  if(contains(to,5.9,11.55,1.82,4.18))return has('bridge')&&(levels.get('bridge')||0)>.999;
  if(contains(to,11.5,20,-.05,8.1))return true;
  if(contains(to,14.5,17.5,-3.2,.2))return true;
  if(contains(to,11.72,19.73,-9.3,-3.05)){if(from.z>-3&&!(from.x>=14.5&&from.x<=17.5))return false;return Math.abs(heightAt(to.x,to.z)-heightAt(from.x,from.z))<.35;}
  return false;
 }
 function interact(id){const spec=targets.find(t=>t.id===id);if(!spec||spec.requires?.some(r=>!actions.has(r)))return false;actions.add(id);levels.set(id,levels.get(id)||0);if(fruitIds.includes(id))fruitGroups[fruitIds.indexOf(id)].visible=false;return true;}
 const inkCommits=new Map();let pondStart=null;
 function setGardenInkEffect(id,value,commit){levels.set(id,T.MathUtils.clamp(value,0,1));if(commit)inkCommits.set(id,commit);if(id==='pond'&&pondStart===null)pondStart=sceneTime;}
 let studyPlayer=null;function updateCamera(camera,dt,player=studyPlayer){if(!(dt>0)||!player||!cameraZones[0].test(player))return;const a=1-Math.exp(-dt*2.8),from=camera.quaternion.clone();camera.position.lerp(V(...cameraZones[0].position),a);camera.lookAt(V(...cameraZones[0].lookAt));const desired=camera.quaternion.clone();camera.quaternion.copy(from).slerp(desired,a);camera.fov=T.MathUtils.lerp(camera.fov,43,a);camera.updateProjectionMatrix();camera.updateMatrixWorld(true);}
 function reset(){actions.clear();levels.clear();inkCommits.clear();sceneTime=0;clock.t=null;pondStart=null;studyPlayer=null;bridge.rotation.z=Math.PI/2;shutters.forEach(({g})=>g.rotation.y=0);fruitGroups.forEach(g=>g.visible=true);fruitGroups[1].position.y=3.5;branch.rotation.y=0;poemLetters.material.opacity=0;pondMaterial.uniforms.time.value=0;pondMaterial.uniforms.inkAge.value=-1;pondMaterial.uniforms.inkPower.value=0;for(const material of cutawayMaterials.values())material.opacity=1;for(const lamp of lanterns){lamp.paper.material.emissiveIntensity=.10;lamp.light.intensity=.20;}for(const l of lotus){l.leaf.scale.set(.05,1,.05);l.flower.scale.setScalar(.06);for(const p of l.petals){p.rotation.x=.02;p.scale.set(.32,.66,.32);}}}
 function update(t,response=0,frameDt){const dt=Number.isFinite(frameDt)?T.MathUtils.clamp(frameDt,0,.06):clock.t===null||clock.t===undefined?0:Math.min(.06,Math.max(0,t-clock.t));clock.t=t;sceneTime+=dt;for(const id of actions)if(!['window','bridge','lamp','pond','poem'].includes(id))levels.set(id,T.MathUtils.damp(levels.get(id)||0,1,1.5,dt));const get=id=>levels.get(id)||0;for(const {g,side} of shutters)g.rotation.y=side*get('window')*1.28;branch.rotation.y=get('window')*-.8+Math.sin(sceneTime*.4)*.025;bridge.rotation.z=(1-get('bridge'))*Math.PI/2;seal.material.emissiveIntensity=actions.has('window')?.75:.10;pondMaterial.uniforms.time.value=sceneTime;pondMaterial.uniforms.inkAge.value=pondStart===null?-1:sceneTime-pondStart;pondMaterial.uniforms.inkPower.value=pondStart===null?0:.50+(inkCommits.get('pond')?.amount||0)*.75;wind.material.opacity=get('window')*(1-get('bridge'))*.33;const attr=windG.attributes.position;for(let i=0;i<attr.count;i++){const u=((sceneTime*.13+i/attr.count)%1);attr.setXYZ(i,-2.8+u*7.4,.7+Math.sin(u*Math.PI)*1.25+Math.sin(i*2)*.18,-.2+u*3.2+Math.cos(i*3)*.23);}attr.needsUpdate=true;fruitGroups[1].position.y=3.5-get('window')*3.02;for(let i=0;i<fruitGroups.length;i++)fruitGroups[i].rotation.z=Math.sin(sceneTime*.7+i)*.02;const lightPower=1.5+(inkCommits.get('lamp')?.amount||0)*2.8;for(const lamp of lanterns){lamp.paper.material.emissiveIntensity=.10+get('lamp')*(.45+lightPower*.13);lamp.light.intensity=.20+get('lamp')*lightPower;}for(const l of lotus){const open=T.MathUtils.smootherstep(get('pond'),l.delay,.70+l.delay);l.leaf.scale.set(.05+open*.95,1,.05+open*.95);l.flower.scale.setScalar(.06+open*.94);for(const p of l.petals){p.rotation.x=.02-open*.95;p.scale.set(.32+open*.68,.66+open*.34,.32+open*.68);}}poemLetters.material.opacity=get('poem');}
 const gateLight=new T.PointLight(0xf1e8c4,1.1,4);scene.add(gateLight);
 const stage={scene,root,update,reset,interact,targets,bounds,heightAt,canMove,cameraZones,updateCamera,walkSurfaces,navigationWaypointRadius:.035,spawn:[0,0,11],gateLight,setGardenInkEffect,gardenActionProgress:id=>levels.get(id)||0,hasGardenAction:id=>actions.has(id),studyReaderFoot:[-2.75,.20,-1.45],gardenStudy:{desk,deskPaper,readerFoot:[-2.75,.20,-1.45],doorFoot:[.3,.20,-1.2],roomBounds:{minX:-6.65,maxX:5.75,minZ:-4.05,maxZ:-1.12},doorBounds:{minX:-.5,maxX:1.1,z:-1},cutawayObjects:studyCutaway},gardenObjects:{desk,deskPaper,bridge,shutters,windowLatch,seal,lanterns,pond,pondMaterial,lotus,poemTable,poemPaper,poemLetters,poemTexture,poemCanvas,rails,topRailLeft,topRailRight,fruitGroups},gardenInkSockets:[{id:'window',inkFace:windowLatch,position:[0,0,.058],width:.65,height:.65},{id:'bridge',inkFace:seal,position:[0,0,.008],width:.70,height:.70},{id:'lamp',inkFace:lanterns[0].paper,position:[0,0,.198],width:.60,height:.70},{id:'pond',inkFace:root,position:[6.78,-.187,7.0],rotation:[-Math.PI/2,0,0],width:1.85,height:1.85,inkColor:0xb4c6a5},{id:'poem',inkFace:root,position:[16,2.892,-9.1],rotation:[-Math.PI/2,0,0],width:1.08,height:.57}]};
 Object.defineProperty(stage,'stageOwnCamera',{get:()=>!!studyPlayer&&cameraZones[0].test(studyPlayer)});stage.updateGardenView=player=>{studyPlayer=player;const inside=!!player&&cameraZones[0].test(player);for(const material of cutawayMaterials.values())material.opacity=inside?.16:1;};
 return decorateGardenInk(stage);
}
